import firebase_admin
from firebase_admin import credentials
from google.cloud import firestore
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
import datetime

# ==========================================
# 1. FIRESTORE DATABASE SETUP
# ==========================================
try:
    db = firestore.Client.from_service_account_json(
        "serviceAccountKey.json",
        project="ageless-domain-304911",
        database="vox-do-app"
    )
    print("[+] Firestore connected successfully.")
except Exception as e:
    print(f"[!] Firestore init error: {e}")
    db = None

def save_to_firestore(collection_name: str, data: dict):
    """Saves a dictionary to a specific Firestore collection."""
    if not db:
        print("[!] Database not initialized.")
        return None
    try:
        doc_ref = db.collection(collection_name).document()
        # Ensure the document knows its own ID for easy frontend updates later
        data['id'] = doc_ref.id 
        data['created_at'] = datetime.datetime.now().isoformat()
        doc_ref.set(data)
        return doc_ref.id
    except Exception as e:
        print(f"[!] Error saving to Firestore ({collection_name}): {e}")
        return None

# ==========================================
# 2. GOOGLE WORKSPACE API SETUP
# ==========================================
def get_google_service(access_token: str, api_name: str, api_version: str):
    """Builds an authenticated client for any Google service."""
    creds = Credentials(token=access_token)
    return build(api_name, api_version, credentials=creds)

def create_google_doc(access_token: str, title: str, content: str):
    """Generates a new Google Doc and inserts text."""
    try:
        service = get_google_service(access_token, 'docs', 'v1')
        # Create empty doc
        doc = service.documents().create(body={'title': title}).execute()
        document_id = doc.get('documentId')
        
        # Insert content
        if content:
            requests = [{'insertText': {'location': {'index': 1}, 'text': content}}]
            service.documents().batchUpdate(
                documentId=document_id, 
                body={'requests': requests}
            ).execute()
            
        print(f"[+] Google Doc created: {title}")
        return f"https://docs.google.com/document/d/{document_id}/edit"
    except Exception as e:
        print(f"[!] Google Docs API Error: {e}")
        return None
    
def create_google_sheet(access_token: str, title: str, headers: list = None):
    """Generates a new Google Sheet and optionally adds column headers."""
    try:
        service = get_google_service(access_token, 'sheets', 'v4')
        
        # 1. Create the empty spreadsheet
        spreadsheet_body = {'properties': {'title': title}}
        sheet = service.spreadsheets().create(body=spreadsheet_body, fields='spreadsheetId').execute()
        spreadsheet_id = sheet.get('spreadsheetId')
        
        # 2. Insert headers into the first row if provided
        if headers:
            body = {'values': [headers]}
            service.spreadsheets().values().update(
                spreadsheetId=spreadsheet_id,
                range='A1',  # Start at the top left cell
                valueInputOption='RAW',
                body=body
            ).execute()
            
        print(f"[+] Google Sheet created: {title}")
        return f"https://docs.google.com/spreadsheets/d/{spreadsheet_id}/edit"
    except Exception as e:
        print(f"[!] Google Sheets API Error: {e}")
        return None

def create_calendar_event(access_token: str, title: str, date_str: str):
    """Adds a task to Google Calendar as an all-day event."""
    try:
        service = get_google_service(access_token, 'calendar', 'v3')
        event_body = {
            'summary': f"VoxDo: {title}",
            'start': {'date': date_str}, # Expects YYYY-MM-DD
            'end': {'date': date_str}
        }
        event = service.events().insert(calendarId='primary', body=event_body).execute()
        print(f"[+] Calendar Event created: {title}")
        return event.get('htmlLink')
    except Exception as e:
        print(f"[!] Google Calendar API Error: {e}")
        return None
    
def create_google_slide(access_token: str, title: str, content: str = "Generated by VoxDo"):
    """Generates a Google Slide and populates the title slide."""
    try:
        service = get_google_service(access_token, 'slides', 'v1')
        # 1. Create the blank presentation
        presentation = service.presentations().create(body={'title': title}).execute()
        presentation_id = presentation.get('presentationId')
        
        # 2. Grab the auto-generated Title and Subtitle text boxes
        slides = presentation.get('slides', [])
        if slides:
            elements = slides[0].get('pageElements', [])
            if len(elements) >= 2:
                title_id = elements[0]['objectId']
                subtitle_id = elements[1]['objectId']
                
                # 3. Inject the text
                requests = [
                    {'insertText': {'objectId': title_id, 'text': title}},
                    {'insertText': {'objectId': subtitle_id, 'text': content}}
                ]
                service.presentations().batchUpdate(
                    presentationId=presentation_id, 
                    body={'requests': requests}
                ).execute()
        
        print(f"[+] Google Slides created with content: {title}")
        return f"https://docs.google.com/presentation/d/{presentation_id}/edit"
    except Exception as e:
        print(f"[!] Google Slides API Error: {e}")
        return None
    
def create_google_form(access_token, title, description=""):
    print(f"[+] Generating Google Form: {title}")
    try:
        credentials = Credentials(token=access_token)
        # 1. Connect to the Forms API
        service = build('forms', 'v1', credentials=credentials)
        
        # 2. Define the basic Form structure
        form_body = {
            "info": {
                "title": title,
                "documentTitle": title,
            }
        }
        
        # 3. Ask Google to create it
        result = service.forms().create(body=form_body).execute()
        form_id = result["formId"]
        
        print(f"[+] Form created successfully! ID: {form_id}")
        
        # 4. Return the URL so the user can open it
        return f"https://docs.google.com/forms/d/{form_id}/edit"
        
    except Exception as e:
        print(f"[ERROR] Failed to create Google Form: {e}")
        return None