import os
import re
from typing import List, Union
from pptx import Presentation

# Ensure the output directory exists
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(BASE_DIR, "generated_files")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def sanitize_filename(name: str) -> str:
    """Removes invalid file characters for Windows/Linux paths."""
    clean = re.sub(r'[\\/*?:"<>|()]', "", name)
    return clean.strip().replace(" ", "_").lower()


def build_presentation_file(topic: str, slide_titles: Union[List[str], str]) -> str:
    """
    Creates a presentation deck (.pptx) based on the outline provided by Gemini.
    """
    # Handle case if LLM passes a single string or comma-separated list
    if isinstance(slide_titles, str):
        slide_titles = [s.strip() for s in slide_titles.split(",") if s.strip()]
    elif not slide_titles:
        slide_titles = ["Introduction", "Core Concepts", "Examples & Applications", "Summary"]

    prs = Presentation()

    # --- Title Slide ---
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    if slide.shapes.title:
        slide.shapes.title.text = topic
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by VoxDo Executive Agent"

    # --- Content Slides ---
    bullet_slide_layout = prs.slide_layouts[1]
    for idx, title_text in enumerate(slide_titles, start=1):
        content_slide = prs.slides.add_slide(bullet_slide_layout)
        
        # Set Title
        if content_slide.shapes.title:
            content_slide.shapes.title.text = f"{idx}. {title_text}"
        
        # Set Bullet Points
        if len(content_slide.placeholders) > 1:
            tf = content_slide.placeholders[1].text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.text = f"Key principles and overview of {title_text}."
            
            p2 = tf.add_paragraph()
            p2.text = "Detailed notes, implementations, and structure."

    # Save presentation with clean filename
    safe_name = sanitize_filename(topic)[:40] or "voxdo_presentation"
    filename = f"{safe_name}.pptx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    prs.save(filepath)
    return filepath