import os
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from typing import List, Dict, Any

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "generated_files")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def build_presentation_file(topic: str, slide_titles: List[str]) -> str:
    """
    Creates a styled presentation deck (.pptx) based on the outline provided by Gemini.
    Returns the relative path to the generated file.
    """
    prs = Presentation()

    # --- Title Slide ---
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]

    title.text = topic
    subtitle.text = "Generated by VoxDo Executive Agent"

    # --- Content Slides ---
    bullet_slide_layout = prs.slide_layouts[1]
    for idx, slide_title in enumerate(slide_titles, start=1):
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        
        # Set Title
        title_shape = shapes.title
        title_shape.text = f"{idx}. {slide_title}"
        
        # Add Bullet Body
        body_shape = shapes.placeholders[1]
        tf = body_shape.text_frame
        tf.word_wrap = True
        
        p = tf.paragraphs[0]
        p.text = f"Key concepts and overview for {slide_title}."
        p.level = 0
        
        p2 = tf.add_paragraph()
        p2.text = "Detailed notes and analysis to be finalized."
        p2.level = 1

    # Save presentation
    filename = f"{topic.lower().replace(' ', '_')}_presentation.pptx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    prs.save(filepath)
    return filepath